// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:SeleniumGridManager.Web.Services.Agent.AgentService.TerminateProcess(System.String)~System.Threading.Tasks.Task" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:SeleniumGridManager.Web.Services.Agent.AgentService.GetAs``1(System.String,System.String)~System.Threading.Tasks.Task{``0}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:Web.Controllers.NodesController.TerminateProcesses(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:Web.Controllers.NodesController.GetScreenshot(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:Web.Controllers.NodesController.StartProcess(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Reliability", "CA2007:Do not directly await a Task", Justification = "Not used in ASP.NET Core. See: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html", Scope = "member", Target = "~M:SeleniumGridManager.Web.Services.Agent.AgentService.StartProcess(System.String)~System.Threading.Tasks.Task" )]

